import hmac
import hashlib
import struct
import time
from binascii import hexlify, unhexlify
from enum import Enum


class DigestAlgo(Enum):
    SHA1 = "SHA1"
    SHA256 = "SHA256"
    SHA512 = "SHA512"


DIGEST_ALGO_MAP = {
    "SHA1": hashlib.sha1,
    "SHA256": hashlib.sha256,
    "SHA512": hashlib.sha512,
}


def get_hotp_impl(*, secret_bytes: bytes, counter: int, make_digest_fn, digits: int = 6) -> int:
    if digits < 5 and digits > 9:
        raise ValueError(f"Expected number of digits: 5-9. Actual: {digits}")

    hmac_obj = hmac.new(secret_bytes, digestmod=make_digest_fn)

    # The HOTP values generated by the HOTP generator are treated as big endian.
    counter_raw = struct.pack(">Q", counter)

    hmac_obj.update(counter_raw)

    digest_res = hmac_obj.digest()
    offset = digest_res[-1] % 16
    truncated = digest_res[offset : offset + 4]
    last_31bits = int(hexlify(truncated), 16) & 0x7FFFFFFF

    hotp_value = last_31bits % 10 ** digits
    return hotp_value


def get_hotp(*, secret_bytes: bytes, counter: int, digest_algo: DigestAlgo, digits: int = 6) -> str:
    make_digest_fn = DIGEST_ALGO_MAP[digest_algo.value]
    hotp_value = get_hotp_impl(secret_bytes=secret_bytes, counter=counter, make_digest_fn=make_digest_fn, digits=digits)
    return f"{hotp_value:0{digits}d}"


def get_totp_impl(
    *,
    unix_time: int,
    secret_bytes: bytes,
    digest_algo: DigestAlgo,
    step_size: int = 30,
    digits: int = 6,
    base_time: int = 0,
) -> str:
    counter = (unix_time - base_time) // step_size
    return get_hotp(secret_bytes=secret_bytes, counter=counter, digest_algo=digest_algo, digits=digits)


def get_totp(
    *, secret_bytes: bytes, digest_algo: DigestAlgo, step_size: int = 30, digits: int = 6, base_time: int = 0
) -> str:
    unix_time = int(time.time())
    return get_totp_impl(
        unix_time=unix_time, secret_bytes=secret_bytes, digest_algo=digest_algo, step_size=step_size, digits=digits
    )


if __name__ == "__main__":
    secret_bytes = b"12345678901234567890"

    for counter in range(10):
        value = get_hotp(secret_bytes=secret_bytes, counter=counter, digest_algo=DigestAlgo.SHA1)
        print(f"The HOTP value of the counter {counter} with 6 digits: {value}")

    for counter in range(10):
        value = get_hotp(secret_bytes=secret_bytes, counter=counter, digest_algo=DigestAlgo.SHA1, digits=7)
        print(f"The HOTP value of the counter {counter} with 7 digits: {value}")

    value = get_totp(secret_bytes=secret_bytes, digest_algo=DigestAlgo.SHA1, digits=7)
    print(f"The TOTP value with 7 digits: {value}")
